
-- CART TABLE --
CREATE TABLE CART (
   CART_NO NUMBER CONSTRAINT PK_CART PRIMARY KEY,
   MEMBER_NO  NUMBER NOT NULL,
   CART_QUANTITY NUMBER,
   CART_SIZE CHAR(1) CHECK(CART_SIZE IN('S','M','L')) NOT NULL,
   PRODUCT_NO NUMBER NOT NULL,

   CONSTRAINT FK_CART_PRODUCT_NO FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO),
   CONSTRAINT FK_CART_MEMBER_NO FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

-- CART_NO SEQUENCE --
CREATE SEQUENCE SEQ_CART_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;



   	SELECT C.*, P.PRODUCT_NAME, P.PRODUCT_PRICE, M.BRAND_NAME, LOWER(ATT_NAME) ATT_NAME
	FROM CART C, PRODUCT P, MEMBER M, ATTACHMENT A
	WHERE C.PRODUCT_NO = P.PRODUCT_NO
    AND P.MEMBER_NO = M.MEMBER_NO
    AND P.PRODUCT_NO = A.PRODUCT_NO
    AND ATT_LEVEL = 1
    AND C.MEMBER_NO = 1;
    


DELETE FROM CART WHERE MEMBER_NO = 21;

-- CART DATA INPUT --
Insert into CART (CART_NO,MEMBER_NO,CART_QUANTITY,CART_SIZE,PRODUCT_NO) values (SEQ_CART_NO.NEXTVAL,21,1,'S',1);
Insert into CART (CART_NO,MEMBER_NO,CART_QUANTITY,CART_SIZE,PRODUCT_NO) values (SEQ_CART_NO.NEXTVAL,21,1,'L',3);
Insert into CART (CART_NO,MEMBER_NO,CART_QUANTITY,CART_SIZE,PRODUCT_NO) values (SEQ_CART_NO.NEXTVAL,21,1,'M',4);
Insert into CART (CART_NO,MEMBER_NO,CART_QUANTITY,CART_SIZE,PRODUCT_NO) values (SEQ_CART_NO.NEXTVAL,21,1,'M',2);
Insert into CART (CART_NO,MEMBER_NO,CART_QUANTITY,CART_SIZE,PRODUCT_NO) values (SEQ_CART_NO.NEXTVAL,21,1,'M',5);

commit;

ROLLBACK;